#!/bin/bash

# This is the environment to be used to do developement for android.
# PLEASE UPDATE THIS NEXT TIME I USE THE ENV WITH MORE INFO ABOUT THE PROJECT
export PROJECT_NAME=droid
export PROJECT_SHORT_NAME=droid

export BUILD_DIR=/media/cdata/dev/droid
export DEPLOY_DIR=/media/cdata/deploy/${PROJECT_SHORT_NAME}
export JAVA_HOME=/usr/lib/jvm/default-java
export CATALINA_HOME=/opt/tomcat

pathadd /media/cdata/apps/apache-maven-3.0.4/bin PATH
pathadd ${JAVA_HOME}/bin PATH
pathadd ${BUILD_DIR}/android-sdk-linux/tools PATH
pathadd ${BUILD_DIR}/android-sdk-linux/platform-tools PATH
