#!/bin/bash

# Project to start getting files and then all personal information organized across
# all of a persons devices and internet footprint

# This first service is to figure out all of the files on a particular device. This is 
# done by searching through the device, and adding all of the file information to a cassandra
# instance.

# Cassandra needs to be running. Currently, this runs under windows. Run cassandra program from bin in the 
# cassandra distribution. There is a cass environment file for doing this.
export PROJECT_NAME=findfiles
export PROJECT_SHORT_NAME=ff

export BUILD_DIR=/vagrant/data/repos/find-files
#export DEPLOY_DIR=/media/cdata/deploy/${PROJECT_SHORT_NAME}
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export CASSANDRA_HOME=/vagrant/data/software/apache-cassandra-3.9

pathadd ${JAVA_HOME}/bin PATH
pathadd ${CASSANDRA_HOME}/bin PATH
