#!/bin/bash

# ANOTHER PROJECT WITH NO DOC
# This was supposed to be able to use your phone like a wand
export PROJECT_NAME=wand
export PROJECT_SHORT_NAME=wand

export BUILD_DIR=/data/dev/mobile-ws/
export DEPLOY_DIR=/data/deploy/mobile-ws/
export JAVA_HOME=/usr/lib/jvm/default-java
export CATALINA_HOME=/data/deploy/tomcat
export CATALINA_BASE=${DEPLOY_DIR}

pathadd ${JAVA_HOME}/bin PATH

