#!/bin/bash

export EMACS_HOME=/active/emacs-23.2/

. /active/python/python.env
. /active/mercurial/mercurial.env
. /active/maven/maven.env
. /active/tmux/tmux.env

export PYTHONPATH=$PYTHONPATH:${DEV_HOME}/shared/python/lib/python2.7/site-packages/

source pathadd-src ${EMACS_HOME}/bin PATH
source pathadd-src /software/int5sys_files/bin PATH

