#!/bin/bash

export EMACS_HOME=/active/emacs-24.4/

. /active/python/python.env
. /active/mercurial/mercurial.env
. /active/git/git.env
. /active/maven/maven.env
. /active/tmux/tmux.env

export PYTHONPATH=$PYTHONPATH:${DEV_HOME}/shared/python/lib/python2.7/site-packages/

source pathadd-src ${EMACS_HOME}/bin PATH

