#!/bin/bash

export EMACS_HOME=/active/emacs-23.3/

. /active/python/python.env
. /active/mercurial/mercurial.env
. /active/maven/maven.env
. /active/emacs/emacs.env

export PYTHONPATH=$PYTHONPATH:${DEV_HOME}/shared/python/lib/python2.7/site-packages/
