#!/bin/bash

# This environment is for Adviser Hadoop (India version)
# Currently project is on ps40, using the Hadoop with a master on ps40

export PROJECT_NAME="Adviser India"
export PROJECT_SHORT_NAME=adviser-in

export BUILD_DIR=~/repos/adviser5
export DEPLOY_DIR=/opt/apache/hadoop/hadoop-2.7.1
export BASE_DIR=${DEPLOY_DIR}

export JAVA_HOME=/active/java8
export HADOOP_CONF_DIR=/opt/apache/hadoop/hadoop-conf-2.7.1
export PGDATA=/opt/postgres/data
export PGHOST=localhost
export PGDATABASE=adviser

export TUCONFIG_CORE=tucanada-devl+ifx

pathadd /home/sparker/bin PATH
pathadd ${JAVA_HOME}/bin PATH
pathadd ${DEPLOY_DIR}/bin PATH
pathadd ${DEPLOY_DIR}/sbin PATH
