#!/bin/bash

export PROJECT_NAME="Adviser"
export PROJECT_SHORT_NAME=adviser

export BUILD_DIR=~/repos/adviser-hadoop
export DEPLOY_DIR=~/apps
export BASE_DIR=${DEPLOY_DIR}

export JAVA_HOME=/active/java8
export HADOOP_CONF_DIR=/etc/opt/apache/hadoop-2.2.0/conf
#export TUCONFIG_CORE=tucanada-perf-dl

. /active/maven3/maven.env
# if M2_HOME is set it can cause problems...
unset M2_HOME
pathadd /active/java8/bin PATH
pathadd ${DEPLOY_DIR}/bin PATH

export TUCONFIG_VERSION=dev