#!/bin/bash

export PROJECT_NAME="Adviser"
export PROJECT_SHORT_NAME=adviser

export BUILD_DIR=~/repos/adviser5
export DEPLOY_DIR=/opt/apache/hadoop/hadoop-2.7.1
export BASE_DIR=${DEPLOY_DIR}

export JAVA_HOME=/active/java8
export HADOOP_CONF_DIR=/opt/apache/hadoop/hadoop-conf-2.7.1
export PGDATA=/opt/postgres/data
export PGHOST=localhost
export PGDATABASE=adviser

export TUCONFIG_CORE=tucanada-devl+ifx

pathadd /home/sparker/bin PATH
pathadd ${JAVA_HOME}/bin PATH
pathadd ${DEPLOY_DIR}/bin PATH
pathadd ${DEPLOY_DIR}/sbin PATH
