#!/bin/bash

export PROJECT_NAME="chile-cs"
export PROJECT_SHORT_NAME=chile-cs

export BUILD_DIR=~/repos/chile/dev/chilecore/
export DEPLOY_DIR=~/apps/chilecore/

export JAVA_HOME=/active/java

pathadd /active/java/bin PATH
pathadd ~/apps/bin PATH
pathadd ${DEPLOY_DIR}/base/bin PATH

export LOG_HOME==${DEPLOY_DIR}/log

export CATALINA_HOME=${INSTALL_DIR}/apache-tomcat-6.0.16
export CATALINA_BASE=${DEPLOY_DIR}/catalina

export TUCONFIG_CHILECORE=tandemless-lb
