#!/bin/bash

export PROJECT_NAME=dataloader
export PROJECT_SHORT_NAME=dl

export BUILD_DIR=/home/sparker/repos/dataloader
export DEPLOY_DIR=/home/sparker/apps/${PROJECT_SHORT_NAME}

export IBF_HOME=${DEPLOY_DIR}/home
export IBF_BASE=${DEPLOY_DIR}/base
export TC_HOME=/active/terracotta
export TC_HOST=tuintlps18.tuintl.transunion.com
export ACTIVEMQ_HOME=/active/apache-activemq
export ACTIVEMQ_BASE=${DEPLOY_DIR}/activemq
export TOMCAT_HOME=${DEPLOY_DIR}/catalina
export CATALINA_HOME=/active/tomcat
export CATALINA_BASE=${DEPLOY_DIR}/catalina

export JAVA_HOME=/active/java

pathadd /active/java/bin PATH
pathadd ${DEPLOY_DIR}/../bin PATH
pathadd ${ACTIVEMQ_HOME}/bin PATH
