#!/bin/bash

export PROJECT_NAME="Hadoop DL"
export PROJECT_SHORT_NAME=hdl

export BUILD_DIR=~/repos/dataloader
export DEPLOY_DIR=~/shared/thirdparty/hadoop-1.1.2
export BASE_DIR=${DEPLOY_DIR}

export JAVA_HOME=/active/java
export HADOOP_CONF_DIR=/shared/sparker/thirdparty/hadoop-base/conf/
export TUCONFIG_CORE=tucanada-perf-dl

pathadd ${JAVA_HOME}/bin PATH
pathadd ${DEPLOY_DIR}/bin PATH
