#!/bin/bash

export PROJECT_NAME="solr"
export PROJECT_SHORT_NAME=solr

export BASE_DIR=~/solr-5.5.1
export BUILD_DIR=${BASE_DIR}
export DEPLOY_DIR=${BASE_DIR}

export JAVA_HOME=/active/java8

. /active/maven/maven.env

pathadd ${JAVA_HOME}/bin PATH
pathadd ${BASE_DIR}/bin PATH

# Docker stuff
export DOCKER_HOST=tcp://tuintlps42:2575
pathadd /shared/sparker/docker/bin PATH

