#!/bin/bash

# For starting cassandra at work

# Downloaded from apache. Run bin/cassandra to start the server

export PROJECT_NAME=work cassandra
export PROJECT_SHORT_NAME=wcass

export CASSANDRA_HOME=/home/sparker/thirdparty/apache-cassandra-3.7
export BUILD_DIR=${CASSANDRA_HOME}
export JAVA_HOME=/active/java8
export CQLSH_HOST=tuintlps41

pathadd ${JAVA_HOME}/bin PATH
pathadd ${CASSANDRA_HOME}/bin PATH
