#!/bin/bash

export PROJECT_NAME=detect-mortgage
export PROJECT_SHORT_NAME=dm

export BUILD_DIR=/home/sparker/shared/repos/detect-mortgage
export REPO_DIR=/home/sparker/shared/repos
export DEPLOY_DIR=/opt/mex/india/dmdeploy

export TOMCAT_HOME=${DEPLOY_DIR}/catalina
export TC_HOME=/home/int5sys/opt/terracotta-2.7.2/
export TC_HOST=localhost
export ACTIVEMQ_HOME=/home/int5sys/opt/apache-activemq-5.2.0
export ACTIVEMQ_BASE=${DEPLOY_DIR}/activeMQ
export CATALINA_HOME=/home/int5sys/opt/apache-tomcat-6.0.18
export CATALINA_BASE=${DEPLOY_DIR}/catalina
export TUCONFIG_PATH_MORTGAGE=${DEPLOY_DIR}/ext-config
export TUCONFIG_MORTGAGE=dev
