#!/bin/bash

export PROJECT_NAME="Express Match"
export PROJECT_SHORT_NAME=em

export BUILD_DIR=~/repos/express-match
export DEPLOY_DIR=~/apps/em

export JAVA_HOME=/active/java8

pathadd /active/java8/bin PATH
pathadd ${DEPLOY_DIR}/bin PATH
