#!/bin/bash

export PROJECT_NAME="Express search"
export PROJECT_SHORT_NAME=express

export BUILD_DIR=~/repos/oematch
export DEPLOY_DIR=~/apphome/oematch
export BASE_DIR=~/apphome/oematch

export JAVA_HOME=/active/java8

pathadd ${JAVA_HOME}/bin PATH

