#!/bin/bash

export PROJECT_NAME="Technology Systems Socket Server - web console"
export PROJECT_SHORT_NAME=tcon

export BUILD_DIR=~/repos/tsss-console
export DEPLOY_DIR=~/apps/tsss-console

export IBF_HOME=${DEPLOY_DIR}/home
export IBF_BASE=${DEPLOY_DIR}/base

export CATALINA_HOME=/active/tomcat
export CATALINA_BASE=${DEPLOY_DIR}/catalina

export JAVA_HOME=/active/java

pathadd /active/java/bin PATH
pathadd ~/apps/bin PATH
